In [24]:
import pandas as pd                           # For working with data
pd.set_option("display.max_columns", None)    # Lets us see all columns of the data instead of just a preview
import geopandas as gpd                       # For working with spatial data
import numpy as np                            # For working with numbers
import matplotlib.pyplot as plt               # For making graphs
from datetime import date                     # For formatting dates
from PIL import Image                         # For getting and displaying images from links
import requests                               # For getting information from links
from io import BytesIO                        # For working with types of input and output

import seaborn as sns
import folium
from folium.plugins import HeatMap

In [25]:
end_date = "2026-01-31"
data = gpd.read_file(f"https://api.globe.gov/search/v1/measurement/?protocols=mosquito_habitat_mapper&datefield=measuredDate&startdate=2018-01-01&enddate={end_date}&geojson=TRUE&sample=FALSE")
land_cover = gpd.read_file(f"https://api.globe.gov/search/v1/measurement/?protocols=land_covers&datefield=measuredDate&startdate=2018-01-01&enddate={end_date}&geojson=TRUE&sample=FALSE")

In [26]:
df = pd.DataFrame(data)
df.to_csv("output.csv", index=False)

In [27]:
data.head(10)

,countryCode,countryName,elevation,mosquitohabitatmapperAbdomenCloseupPhotoUrls,mosquitohabitatmapperBreedingGroundEliminated,mosquitohabitatmapperComments,mosquitohabitatmapperDataSource,mosquitohabitatmapperExtraData,mosquitohabitatmapperGenus,mosquitohabitatmapperGlobeTeams,mosquitohabitatmapperLarvaFullBodyPhotoUrls,mosquitohabitatmapperLarvaeCount,mosquitohabitatmapperLastIdentifyStage,mosquitohabitatmapperLocationAccuracyM,mosquitohabitatmapperLocationMethod,mosquitohabitatmapperMeasuredAt,mosquitohabitatmapperMeasurementElevation,mosquitohabitatmapperMeasurementLatitude,mosquitohabitatmapperMeasurementLongitude,mosquitohabitatmapperMosquitoAdults,mosquitohabitatmapperMosquitoEggCount,mosquitohabitatmapperMosquitoEggs,mosquitohabitatmapperMosquitoHabitatMapperId,mosquitohabitatmapperMosquitoPupae,mosquitohabitatmapperSpecies,mosquitohabitatmapperUserid,mosquitohabitatmapperWaterSource,mosquitohabitatmapperWaterSourcePhotoUrls,mosquitohabitatmapperWaterSourceType,organizationId,organizationName,protocol,siteId,siteName,geometry
0,USA,United States,59.3,null,false,null,GLOBE Observer App,LarvaeVisibleNo,null,NaN,null,0,null,29,automatic,2026-01-31 00:31:00,0,32.7151,-117.1295,null,null,null,50487,false,null,178205484,tree holes,https://data.globe.gov/system/photos/2026/01/3...,container: natural,17043304,United States of America Citizen Science,mosquito_habitat_mapper,409674,11SMS878197,POINT (-117.13018 32.715)
1,USA,United States,5.9,null,false,null,GLOBE Observer App,LarvaeVisibleYes,null,NaN,null,null,identify-photo-larva,18,automatic,2026-01-30 22:21:00,0,21.319,-158.024,null,null,null,50486,false,null,178278578,"plant husk (areca, coconut etc)",pending approval,container: natural,17043304,United States of America Citizen Science,mosquito_habitat_mapper,409671,04QFJ012577,POINT (-158.02421 21.3184)
2,BRA,Brazil,13.0,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,"[COLUNanoII, COLUNSLZ]",null,0,null,13,automatic,2026-01-29 14:17:00,0,-2.5462,-44.3257,null,null,null,50378,false,null,137422345,other,https://data.globe.gov/system/photos/2026/01/2...,container: artificial,17459532,Brazil Citizen Science,mosquito_habitat_mapper,373830,23MNT749185,POINT (-44.32625 -2.54662)
3,THA,Thailand,146.9,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,NaN,null,null,identify,null,manual,2026-01-26 08:17:00,0,16.3629,103.4308,null,null,null,50369,false,null,178884320,other,null,container: artificial,48451737,Anukoolnaree School,mosquito_habitat_mapper,409216,48QUD323097,POINT (103.42989 16.36267)
4,THA,Thailand,7.0,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,[GLOBE PCSHSTrang],null,30,identify-later,null,manual,2026-01-26 07:45:00,0,7.5552,99.5567,true,null,false,50360,true,null,132602739,tire,https://data.globe.gov/system/photos/2026/01/2...,container: artificial,163028,Princess Chulabhorn Science High School Trang,mosquito_habitat_mapper,210710,47NNJ614351,POINT (99.55658 7.55462)
5,THA,Thailand,145.9,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,NaN,https://data.globe.gov/system/photos/2026/01/2...,null,identify-photo-abdomen,null,manual,2026-01-26 01:30:00,0,16.3871,103.473,null,null,null,50358,false,null,178884320,"cement, metal or plastic tank",null,container: artificial,48451737,Anukoolnaree School,mosquito_habitat_mapper,409189,48QUD369123,POINT (103.47276 16.38648)
6,THA,Thailand,144.6,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,NaN,null,null,identify,null,manual,2026-01-26 08:13:00,0,16.4058,103.464,null,null,null,50364,false,null,178884320,"cement, metal or plastic tank",null,container: artificial,48451737,Anukoolnaree School,mosquito_habitat_mapper,409211,48QUD359144,POINT (103.46325 16.40539)
7,THA,Thailand,164.1,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,NaN,null,null,identify,null,manual,2026-01-26 08:15:00,0,16.3864,103.4284,null,null,null,50367,false,null,178884320,other,null,container: artificial,48451737,Anukoolnaree School,mosquito_habitat_mapper,409214,48QUD321123,POINT (103.42783 16.38615)
8,THA,Thailand,7.0,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,[GLOBE PCSHSTrang],https://data.globe.gov/system/photos/2026/01/2...,null,identify-photo-abdomen,null,manual,2026-01-26 07:55:00,0,7.5551,99.5568,null,null,null,50361,false,null,132602739,"cement, metal or plastic tank",https://data.globe.gov/system/photos/2026/01/2...,container: artificial,163028,Princess Chulabhorn Science High School Trang,mosquito_habitat_mapper,210710,47NNJ614351,POINT (99.55658 7.55462)
9,THA,Thailand,145.9,null,false,null,GLOBE Observer App,LarvaeVisibleYes,null,NaN,null,null,identify,null,manual,2026-01-26 08:11:00,0,16.3871,103.473,null,null,null,50362,false,null,178884320,"cement, metal or plastic tank",null,container: artificial,48451737,Anukoolnaree School,mosquito_habitat_mapper,409189,48QUD369123,POINT (103.47276 16.38648)

In [30]:
#data.head()
data.shape

(47394, 35)

In [31]:
data.columns

Index(['countryCode', 'countryName', 'elevation',
       'mosquitohabitatmapperAbdomenCloseupPhotoUrls',
       'mosquitohabitatmapperBreedingGroundEliminated',
       'mosquitohabitatmapperComments', 'mosquitohabitatmapperDataSource',
       'mosquitohabitatmapperExtraData', 'mosquitohabitatmapperGenus',
       'mosquitohabitatmapperGlobeTeams',
       'mosquitohabitatmapperLarvaFullBodyPhotoUrls',
       'mosquitohabitatmapperLarvaeCount',
       'mosquitohabitatmapperLastIdentifyStage',
       'mosquitohabitatmapperLocationAccuracyM',
       'mosquitohabitatmapperLocationMethod',
       'mosquitohabitatmapperMeasuredAt',
       'mosquitohabitatmapperMeasurementElevation',
       'mosquitohabitatmapperMeasurementLatitude',
       'mosquitohabitatmapperMeasurementLongitude',
       'mosquitohabitatmapperMosquitoAdults',
       'mosquitohabitatmapperMosquitoEggCount',
       'mosquitohabitatmapperMosquitoEggs',
       'mosquitohabitatmapperMosquitoHabitatMapperId',
       'mosquitohabitatmapperMosquitoPupae', 'mosquitohabitatmapperSpecies',
       'mosquitohabitatmapperUserid', 'mosquitohabitatmapperWaterSource',
       'mosquitohabitatmapperWaterSourcePhotoUrls',
       'mosquitohabitatmapperWaterSourceType', 'organizationId',
       'organizationName', 'protocol', 'siteId', 'siteName', 'geometry'],
      dtype='str')

In [32]:
data.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 47394 entries, 0 to 47393
Data columns (total 35 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   countryCode                                    47308 non-null  str
 1   countryName                                    47308 non-null  str
 2   elevation                                      47394 non-null  str
 3   mosquitohabitatmapperAbdomenCloseupPhotoUrls   47394 non-null  str
 4   mosquitohabitatmapperBreedingGroundEliminated  47394 non-null  str
 5   mosquitohabitatmapperComments                  47394 non-null  str
 6   mosquitohabitatmapperDataSource                47394 non-null  str
 7   mosquitohabitatmapperExtraData                 47394 non-null  str
 8   mosquitohabitatmapperGenus                     47394 non-null  str
 9   mosquitohabitatmapperGlobeTeams                18001 non-null  str
 10  mosquitohabitatmapperLarvaFullBodyPhotoUrls    47394 non-null  str
 11  mosquitohabitatmapperLarvaeCount               47394 non-null  str
 12  mosquitohabitatmapperLastIdentifyStage         47394 non-null  str
 13  mosquitohabitatmapperLocationAccuracyM         29053 non-null  str
 14  mosquitohabitatmapperLocationMethod            29053 non-null  str
 15  mosquitohabitatmapperMeasuredAt                47394 non-null  datetime64[ms]
 16  mosquitohabitatmapperMeasurementElevation      47377 non-null  str
 17  mosquitohabitatmapperMeasurementLatitude       47377 non-null  str
 18  mosquitohabitatmapperMeasurementLongitude      47377 non-null  str
 19  mosquitohabitatmapperMosquitoAdults            47394 non-null  str
 20  mosquitohabitatmapperMosquitoEggCount          47394 non-null  str
 21  mosquitohabitatmapperMosquitoEggs              47394 non-null  str
 22  mosquitohabitatmapperMosquitoHabitatMapperId   47394 non-null  str
 23  mosquitohabitatmapperMosquitoPupae             47394 non-null  str
 24  mosquitohabitatmapperSpecies                   47394 non-null  str
 25  mosquitohabitatmapperUserid                    47394 non-null  str
 26  mosquitohabitatmapperWaterSource               47394 non-null  str
 27  mosquitohabitatmapperWaterSourcePhotoUrls      47394 non-null  str
 28  mosquitohabitatmapperWaterSourceType           47394 non-null  str
 29  organizationId                                 47394 non-null  str
 30  organizationName                               47308 non-null  str
 31  protocol                                       47394 non-null  str
 32  siteId                                         47394 non-null  str
 33  siteName                                       47394 non-null  str
 34  geometry                                       47394 non-null  geometry
dtypes: datetime64[ms](1), geometry(1), str(33)
memory usage: 12.7 MB

In [39]:
fl_Mos_data = data[data["countryName"] == "United States"].copy()
fl_Mos_data = fl_Mos_data.cx[-87.7:-79.6, 24.4:31.1]

In [40]:
fl_Mos_data

,countryCode,countryName,elevation,mosquitohabitatmapperAbdomenCloseupPhotoUrls,mosquitohabitatmapperBreedingGroundEliminated,mosquitohabitatmapperComments,mosquitohabitatmapperDataSource,mosquitohabitatmapperExtraData,mosquitohabitatmapperGenus,mosquitohabitatmapperGlobeTeams,mosquitohabitatmapperLarvaFullBodyPhotoUrls,mosquitohabitatmapperLarvaeCount,mosquitohabitatmapperLastIdentifyStage,mosquitohabitatmapperLocationAccuracyM,mosquitohabitatmapperLocationMethod,mosquitohabitatmapperMeasuredAt,mosquitohabitatmapperMeasurementElevation,mosquitohabitatmapperMeasurementLatitude,mosquitohabitatmapperMeasurementLongitude,mosquitohabitatmapperMosquitoAdults,mosquitohabitatmapperMosquitoEggCount,mosquitohabitatmapperMosquitoEggs,mosquitohabitatmapperMosquitoHabitatMapperId,mosquitohabitatmapperMosquitoPupae,mosquitohabitatmapperSpecies,mosquitohabitatmapperUserid,mosquitohabitatmapperWaterSource,mosquitohabitatmapperWaterSourcePhotoUrls,mosquitohabitatmapperWaterSourceType,organizationId,organizationName,protocol,siteId,siteName,geometry
941,USA,United States,14.0,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,NaN,null,0,null,23,automatic,2025-11-04 17:41:00,0,30.5089,-86.5028,null,null,null,49205,false,null,159641339,jar,https://data.globe.gov/system/photos/2025/11/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,403045,16REU477752,POINT (-86.50288 30.50815)
942,USA,United States,14.0,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,NaN,null,0,null,null,manual,2025-11-04 20:38:00,0,30.5088,-86.5028,null,null,null,49206,false,null,159641339,jar,https://data.globe.gov/system/photos/2025/11/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,403045,16REU477752,POINT (-86.50288 30.50815)
1282,USA,United States,2.8,null,false,Canal in City running from inland to ocean.,GLOBE Observer App,LarvaeVisibleNo,null,NaN,null,0,null,20,automatic,2025-10-08 12:15:00,0,26.2154,-80.2169,null,null,null,48840,false,null,171829152,"puddle or still water next to a creek, stream ...",null,flowing: still water found next to river or st...,10532858,GLOBE Implementation Office GLOBE v-School,mosquito_habitat_mapper,400104,17RNJ782997,POINT (-80.21719 26.21473)
3160,USA,United States,3.5,null,false,null,GLOBE Observer App,LarvaeVisibleNo,null,NaN,null,0,null,31,automatic,2025-03-12 18:24:00,0,28.3521,-80.6053,null,null,null,46774,false,null,148137248,plant clumps (bamboo etc),https://data.globe.gov/system/photos/2025/03/1...,container: natural,17043304,United States of America Citizen Science,mosquito_habitat_mapper,380362,17RNM386362,POINT (-80.60613 28.35146)
3171,USA,United States,43.6,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,NaN,null,12,identify,12,automatic,2025-03-07 18:41:00,0,28.2852,-81.6414,true,null,false,46775,true,null,36036190,estuary,null,flowing: still water found next to river or st...,10532858,GLOBE Implementation Office GLOBE v-School,mosquito_habitat_mapper,380476,17RMM371289,POINT (-81.64142 28.28463)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42494,USA,United States,25.4,null,false,null,GLOBE Observer App,null,null,NaN,null,null,null,NaN,NaN,2018-12-29 21:38:00,0,28.1411,-82.4335,null,null,null,6217,false,null,2521381,fountain or bird bath,null,container: artificial,394556,University Of Toledo,mosquito_habitat_mapper,143714,17RLM592136,POINT (-82.4338 28.14052)
42495,USA,United States,25.4,null,true,null,GLOBE Observer App,null,null,NaN,null,3,identify,NaN,NaN,2018-12-29 22:30:00,0,28.1408,-82.4334,false,null,true,6220,true,null,51180976,can or bottle,https://data.globe.gov/system/photos/2018/12/2...,container: artificial,51181115,Graves Elementary,mosquito_habitat_mapper,143718,17RLM592136,POINT (-82.4338 28.14052)
45208,USA,United States,6.5,null,true,null,GLOBE Observer App,null,null,NaN,https://data.globe.gov/system/photos/2018/07/2...,28,identify-saddle-complete,NaN,NaN,2018-07-26 14:54:00,0,30.3242,-87.6961,true,null,false,3492,false,null,46168580,tire,https://data.globe.gov/system/photos/2018/07/2...,container: artificial,44821191,STEM Enhancement in Earth Sciences,mosquito_habitat_mapper,133946,16RDU330549,POINT (-87.69694 30.32406)
45223,USA,United States,1.7,null,true,null,GLOBE Observer App,null,Anopheles,NaN,https://data.globe.gov/system/photos/2018/07/2...,8,identify,NaN,NaN,2018-07-26 14:28:00,0,30.3208,-87.6955,false,null,false,3490,true,null,46168580,other,https://data.globe.gov/system/photos/2018/07/2...,container: artificial,44821191,STEM Enhancement in Earth Sciences,mosquito_habitat_mapper,133944,16RDU331545,POINT (-87.69588 30.32045)
46844,USA,United States,5.9,null,true,null,GLOBE Observer App,null,null,NaN,null,null,null,NaN,NaN,2018-03-17 16:09:00,5.9,26.45808,-80.142329,null,null,null,1886,null,null,38752608,fountain or bird bath,https://data.globe.gov/system/photos/2018/03/1...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,109708,17RNK855267,POINT (-80.14233 26.45808)

In [41]:
fl_Mos_data.shape

(625, 35)

In [36]:
fl_landcover = land_cover[
    (land_cover["countryCode"] == "USA") & (land_cover.geometry.x.between(-87.7, -79.6)) & (land_cover.geometry.y.between(24.4, 31.1))
].copy()

In [37]:
fl_landcover.shape

(690, 63)

In [38]:
fl_landcover

,countryCode,countryName,elevation,landcoversDataSource,landcoversDownwardCaption,landcoversDownwardExtraData,landcoversDownwardPhotoUrl,landcoversDryGround,landcoversEastCaption,landcoversEastClassifications,landcoversEastExtraData,landcoversEastPhotoUrl,landcoversFeature1Caption,landcoversFeature1ExtraData,landcoversFeature1PhotoUrl,landcoversFeature2Caption,landcoversFeature2ExtraData,landcoversFeature2PhotoUrl,landcoversFeature3Caption,landcoversFeature3ExtraData,landcoversFeature3PhotoUrl,landcoversFeature4Caption,landcoversFeature4ExtraData,landcoversFeature4PhotoUrl,landcoversFieldNotes,landcoversGlobeTeams,landcoversLandCoverId,landcoversLeavesOnTrees,landcoversLocationAccuracyM,landcoversLocationMethod,landcoversMeasuredAt,landcoversMeasurementElevation,landcoversMeasurementLatitude,landcoversMeasurementLongitude,landcoversMucCode,landcoversMucDescription,landcoversMucDetails,landcoversMuddy,landcoversNorthCaption,landcoversNorthClassifications,landcoversNorthExtraData,landcoversNorthPhotoUrl,landcoversRainingSnowing,landcoversSnowIce,landcoversSouthCaption,landcoversSouthClassifications,landcoversSouthExtraData,landcoversSouthPhotoUrl,landcoversStandingWater,landcoversUpwardCaption,landcoversUpwardExtraData,landcoversUpwardPhotoUrl,landcoversUserid,landcoversWestCaption,landcoversWestClassifications,landcoversWestExtraData,landcoversWestPhotoUrl,organizationId,organizationName,protocol,siteId,siteName,geometry
602,USA,United States,51.2,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2026/01/0...,true,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 231, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 312, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 314, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,Standing decidusous broadleaf trees,"((compassData.heading: 169, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,Cutdown trees to west.,"[HTLC, OpeningTheAperture EarthAsArt, Oregon H...",88833,true,5,automatic,2026-01-02 19:47:00.000,48.3,28.6467,-81.7105,null,null,,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,null,null,https://data.globe.gov/system/photos/2026/01/0...,8267248,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,32402168,"College of Earth, Ocean, Atmospheric Sciences ...",land_covers,407606,17RMM305690,POINT (-81.71114 28.64624)
606,USA,United States,41.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2026/01/0...,true,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 287, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 67, compassData.horizon...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 155, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 227, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,Observation tower at tree canopy height. Everg...,"[HTLC, OpeningTheAperture EarthAsArt, Oregon H...",88836,true,5,automatic,2026-01-02 19:34:00.000,34.7,28.6474,-81.7085,null,null,,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,null,null,https://data.globe.gov/system/photos/2026/01/0...,8267248,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,32402168,"College of Earth, Ocean, Atmospheric Sciences ...",land_covers,407608,17RMM307691,POINT (-81.7091 28.64716)
607,USA,United States,41.4,GLOBE Observer App,null,null,null,true,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,Duplicate location with manual photos,"[HTLC, OpeningTheAperture EarthAsArt, Oregon H...",88835,true,4,automatic,2026-01-02 19:36:00.000,34.7,28.6474,-81.7085,null,null,,false,null,null,null,null,false,false,null,null,null,null,false,null,null,null,8267248,null,null,null,null,32402168,"College of Earth, Ocean, Atmospheric Sciences ...",land_covers,407608,17RMM307691,POINT (-81.7091 28.64716)
614,USA,United States,43.9,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2026/01/0...,true,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 328, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 231, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,Trail with whitish material,"((compassData.heading: 131, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 61, compassData.horizon...",https://data.globe.gov/system/photos/2026/01/0...,(none),"[HTLC, OpeningTheAperture EarthAsArt, Oregon H...",88834,true,5,automatic,2026-01-02 19:42:00.000,43.1,28.6472,-81.71,null,null,,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,null,null,https://data.globe.gov/system/photos/2026/01/0...,8267248,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,32402168,"College of Earth, Ocean, Atmospheric Sciences ...",land_covers,407607,17RMM306691,POINT (-81.71012 28.64715)
707,USA,United States,2.1,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2025/12/2...,true,null,null,null,https://data.globe.gov/system/photos/2025/12/2...,null,null,null,null,null,null,null,null,null,null,null,null,(none),[NASA Response Mappers],88712,true,4,automatic,2025-12-23 19:58:00.000,2.2,25.6479,-80.3833,null,null,,false,null,null,null,https://data.globe.gov/system/photos/2025/12/2...,false,false,null,null,null,https://data.globe.gov/system/photos/2025/12/2...,false,null,null,https://data.globe.gov/system/photos/2025/12/2...,120475683,null,null,null,https://data.globe.gov/system/photos/2025/12/2...,17043304,United States of America Citizen Science,land_covers,394594,17RNJ619368,POINT (-80.38332 25.64757)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58144,USA,United States,14.4,GLOBE Observer App,,"(source: app, (compassData.heading: 147.638908...",https://data.globe.gov/system/photos/2019/03/2...,true,,"20% MUC 01 (n) [Trees, Closely Spaced, Evergre...","(source: app, (compassData.heading: 93.9896206...",https://data.globe.gov/system/photos/2019/03/2...,null,null,null,null,null,null,null,null,null,null,null,null,(none),NaN,22012,true,10,automatic,2019-03-21 16:46:00.000,8.1,29.9226,-81.4174,M92,"Urban, Commercial Property",,false,,"20% MUC 01 (n) [Trees, Closely Spaced, Evergre...","(source: app, (compassData.heading: 358.015319...",https://data.globe.gov/system/photos/2019/03/2...,false,false,,"20% MUC 01 (n) [Trees, Closely Spaced, Evergre...","(source: app, (compassData.heading: 177.494270...",https://data.globe.gov/system/photos/2019/03/2...,false,,"(source: app, (compassData.heading: 292.699996...",https://data.globe.gov/system/photos/2019/03/2...,24007076,,"10% MUC 01 (n) [Trees, Closely Spaced, Evergre...","(source: app, (compassData.heading: 271.356033...",https://data.globe.gov/system/photos/2019/03/2...,17043304,United States of America Citizen Science,land_covers,148173,17RMP597102,POINT (-81.41752 29.92186)
58235,USA,United States,3.7,GLOBE Observer App,,"(source: app, (compassData.heading: 186.175346...",https://data.globe.gov/system/photos/2019/03/1...,true,,null,"(source: app, (compassData.heading: 90.2919456...",https://data.globe.gov/system/photos/2019/03/1...,null,null,null,null,null,null,null,null,null,null,null,null,No recent or planned changes (except to possib...,NaN,2282,true,65,automatic,2019-03-16 16:33:00.000,8.1,29.961,-81.5346,null,null,,false,,null,"(source: app, (compassData.heading: 1.82150268...",https://data.globe.gov/system/photos/2019/03/1...,false,false,,null,"(source: app, (compassData.heading: 181.046768...",https://data.globe.gov/system/photos/2019/03/1...,false,,"(source: app, (compassData.heading: 169.329292...",https://data.globe.gov/system/photos/2019/03/1...,24007076,,null,"(source: app, (compassData.heading: 267.202651...",https://data.globe.gov/system/photos/2019/03/1...,17043304,United States of America Citizen Science,land_covers,104018,17RMP484145,POINT (-81.53479 29.96024)
58668,USA,United States,7.2,GLOBE Observer App,,"(source: app, (compassData.heading: 126.497680...",https://data.globe.gov/system/photos/2019/02/1...,true,,null,"(source: app, (compassData.heading: 93.4000549...",https://data.globe.gov/system/photos/2019/02/1...,null,null,null,null,null,null,null,null,null,null,null,null,(none),NaN,1913,true,null,manual,2019-02-19 12:29:00.000,-263.2,26.5935,-80.1683,null,null,,false,,null,"(source: app, (compassData.heading: 3.08322906...",https://data.globe.gov/system/photos/2019/02/1...,false,false,,null,"(source: app, (compassData.heading: 185.371124...",https://data.globe.gov/system/photos/2019/02/1...,false,,"(source: app, (compassData.heading: 38.3885955...",https://data.globe.gov/system/photos/2019/02/1...,27492755,,null,"(source: app, (compassData.heading: 271.863182...",https://data.globe.gov/system/photos/2019/02/1...,17043304,United States of America Citizen Science,land_covers,69761,17RNK828416,POINT (-80.16844 26.59276)
59825,USA,United States,3.7,GLOBE Observer App,null,null,null,false,,null,(source: camera),https://data.globe.gov/system/photos/2018/10/2...,null,null,null,null,null,null,null,null,null,null,null,null,(none),NaN,952,true,null,manual,2018-10-20 20:39:00.000,-609.7,25.8298,-80.1979,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2018/10/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2018/10/2...,false,null,null,null,48131703,,null,(source: camera),https://data.globe.gov/system/photos/2018/10/2...,17043304,United States of America Citizen Science,land_covers,139976,17RNJ803570,POINT (-80.1988 25.82908)
60898,USA,United States,1.7,GLOBE Data Entry Site Definition,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,NaN,20599,null,null,null,2018-08-07 14:14:33.585,NaN,NaN,NaN,M9,Urban,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,7908704,Walter C. Young Middle,land_covers,134661,Green Young Knights,POINT (-80.32215 26.0141)

In [43]:
fl_merged_data = pd.merge(fl_landcover, fl_Mos_data, on="siteId")

In [44]:
fl_merged_data.shape

(178, 97)

In [45]:
fl_merged_data

,countryCode_x,countryName_x,elevation_x,landcoversDataSource,landcoversDownwardCaption,landcoversDownwardExtraData,landcoversDownwardPhotoUrl,landcoversDryGround,landcoversEastCaption,landcoversEastClassifications,landcoversEastExtraData,landcoversEastPhotoUrl,landcoversFeature1Caption,landcoversFeature1ExtraData,landcoversFeature1PhotoUrl,landcoversFeature2Caption,landcoversFeature2ExtraData,landcoversFeature2PhotoUrl,landcoversFeature3Caption,landcoversFeature3ExtraData,landcoversFeature3PhotoUrl,landcoversFeature4Caption,landcoversFeature4ExtraData,landcoversFeature4PhotoUrl,landcoversFieldNotes,landcoversGlobeTeams,landcoversLandCoverId,landcoversLeavesOnTrees,landcoversLocationAccuracyM,landcoversLocationMethod,landcoversMeasuredAt,landcoversMeasurementElevation,landcoversMeasurementLatitude,landcoversMeasurementLongitude,landcoversMucCode,landcoversMucDescription,landcoversMucDetails,landcoversMuddy,landcoversNorthCaption,landcoversNorthClassifications,landcoversNorthExtraData,landcoversNorthPhotoUrl,landcoversRainingSnowing,landcoversSnowIce,landcoversSouthCaption,landcoversSouthClassifications,landcoversSouthExtraData,landcoversSouthPhotoUrl,landcoversStandingWater,landcoversUpwardCaption,landcoversUpwardExtraData,landcoversUpwardPhotoUrl,landcoversUserid,landcoversWestCaption,landcoversWestClassifications,landcoversWestExtraData,landcoversWestPhotoUrl,organizationId_x,organizationName_x,protocol_x,siteId,siteName_x,geometry_x,countryCode_y,countryName_y,elevation_y,mosquitohabitatmapperAbdomenCloseupPhotoUrls,mosquitohabitatmapperBreedingGroundEliminated,mosquitohabitatmapperComments,mosquitohabitatmapperDataSource,mosquitohabitatmapperExtraData,mosquitohabitatmapperGenus,mosquitohabitatmapperGlobeTeams,mosquitohabitatmapperLarvaFullBodyPhotoUrls,mosquitohabitatmapperLarvaeCount,mosquitohabitatmapperLastIdentifyStage,mosquitohabitatmapperLocationAccuracyM,mosquitohabitatmapperLocationMethod,mosquitohabitatmapperMeasuredAt,mosquitohabitatmapperMeasurementElevation,mosquitohabitatmapperMeasurementLatitude,mosquitohabitatmapperMeasurementLongitude,mosquitohabitatmapperMosquitoAdults,mosquitohabitatmapperMosquitoEggCount,mosquitohabitatmapperMosquitoEggs,mosquitohabitatmapperMosquitoHabitatMapperId,mosquitohabitatmapperMosquitoPupae,mosquitohabitatmapperSpecies,mosquitohabitatmapperUserid,mosquitohabitatmapperWaterSource,mosquitohabitatmapperWaterSourcePhotoUrls,mosquitohabitatmapperWaterSourceType,organizationId_y,organizationName_y,protocol_y,siteName_y,geometry_y
0,USA,United States,2.8,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2025/10/0...,false,null,"10% MUC 01 (b) [Trees, Closely Spaced, Evergre...",null,https://data.globe.gov/system/photos/2025/10/0...,null,null,null,null,null,null,null,null,null,null,null,null,House and yard on canal,NaN,86094,true,null,manual,2025-10-05 22:55:00,2,26.2152,-80.2169,M91,"Urban, Residential Property",,false,null,"10% MUC 02 (n) [Trees, Closely Spaced, Deciduo...",null,https://data.globe.gov/system/photos/2025/10/0...,false,false,null,"30% MUC 01 (b) [Trees, Closely Spaced, Evergre...",null,https://data.globe.gov/system/photos/2025/10/0...,false,null,null,https://data.globe.gov/system/photos/2025/10/0...,171829152,null,"10% MUC 01 (b) [Trees, Closely Spaced, Evergre...",null,https://data.globe.gov/system/photos/2025/10/0...,10532858,GLOBE Implementation Office GLOBE v-School,land_covers,400104,17RNJ782997,POINT (-80.21719 26.21473),USA,United States,2.8,null,false,Canal in City running from inland to ocean.,GLOBE Observer App,LarvaeVisibleNo,null,NaN,null,0,null,20,automatic,2025-10-08 12:15:00,0,26.2154,-80.2169,null,null,null,48840,false,null,171829152,"puddle or still water next to a creek, stream ...",null,flowing: still water found next to river or st...,10532858,GLOBE Implementation Office GLOBE v-School,mosquito_habitat_mapper,17RNJ782997,POINT (-80.21719 26.21473)
1,USA,United States,6.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2023/06/1...,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,null,null,null,null,null,null,null,null,null,null,null,null,This is in my backyard where I am doing my mos...,[SEES2023],59779,true,null,manual,2023-06-15 15:35:00,6,27.5877,-80.4441,null,null,,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,false,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,null,null,https://data.globe.gov/system/photos/2023/06/1...,106918405,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,17043304,United States of America Citizen Science,land_covers,317215,17RNL548516,POINT (-80.44476 27.58721),USA,United States,6.4,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,[SEES2023],null,31,identify,null,manual,2023-06-29 20:27:00,0,27.5877,-80.4438,null,null,null,43291,false,null,106918405,"cement, metal or plastic tank",https://data.globe.gov/system/photos/2023/06/2...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNL548516,POINT (-80.44476 27.58721)
2,USA,United States,6.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2023/06/1...,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,null,null,null,null,null,null,null,null,null,null,null,null,This is in my backyard where I am doing my mos...,[SEES2023],59779,true,null,manual,2023-06-15 15:35:00,6,27.5877,-80.4441,null,null,,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,false,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,null,null,https://data.globe.gov/system/photos/2023/06/1...,106918405,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,17043304,United States of America Citizen Science,land_covers,317215,17RNL548516,POINT (-80.44476 27.58721),USA,United States,6.4,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,[SEES2023],null,0,null,null,manual,2023-06-22 19:17:00,0,27.5877,-80.4441,null,null,null,43207,false,null,106918405,"cement, metal or plastic tank",https://data.globe.gov/system/photos/2023/06/2...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNL548516,POINT (-80.44476 27.58721)
3,USA,United States,6.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2023/06/1...,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,null,null,null,null,null,null,null,null,null,null,null,null,This is in my backyard where I am doing my mos...,[SEES2023],59779,true,null,manual,2023-06-15 15:35:00,6,27.5877,-80.4441,null,null,,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,false,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,null,null,https://data.globe.gov/system/photos/2023/06/1...,106918405,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,17043304,United States of America Citizen Science,land_covers,317215,17RNL548516,POINT (-80.44476 27.58721),USA,United States,6.4,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,[SEES2023],null,0,null,null,manual,2023-06-22 19:16:00,0,27.5877,-80.4441,null,null,null,43206,false,null,106918405,"cement, metal or plastic tank",https://data.globe.gov/system/photos/2023/06/2...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNL548516,POINT (-80.44476 27.58721)
4,USA,United States,6.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2023/06/1...,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,null,null,null,null,null,null,null,null,null,null,null,null,This is in my backyard where I am doing my mos...,[SEES2023],59779,true,null,manual,2023-06-15 15:35:00,6,27.5877,-80.4441,null,null,,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,false,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,null,null,https://data.globe.gov/system/photos/2023/06/1...,106918405,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,17043304,United States of America Citizen Science,land_covers,317215,17RNL548516,POINT (-80.44476 27.58721),USA,United States,6.4,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,[SEES2023],https://data.globe.gov/system/photos/2023/06/2...,21,identify-siphon-pecten,null,manual,2023-06-22 19:21:00,0,27.5877,-80.4441,null,null,null,43205,false,null,106918405,"cement, metal or plastic tank",https://data.globe.gov/system/photos/2023/06/2...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNL548516,POINT (-80.44476 27.58721)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,false,This is for my experiment and used red food dy...,GLOBE Observer App,null,null,[SEES2019],null,0,identify,NaN,NaN,2019-08-02 22:50:00,0,26.3343,-80.1143,true,null,false,14718,false,null,58004254,jar,https://data.globe.gov/system/photos/2019/08/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)
174,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,false,This is for my experiment and used a orange co...,GLOBE Observer App,null,null,[SEES2019],null,0,identify,NaN,NaN,2019-08-02 22:46:00,0,26.3343,-80.1144,true,null,false,14715,false,null,58004254,jar,https://data.globe.gov/system/photos/2019/08/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)
175,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,false,This is for my experiment and used a black con...,GLOBE Observer App,null,null,[SEES2019],null,0,identify,NaN,NaN,2019-08-02 22:49:00,0,26.3343,-80.1143,true,null,false,14717,false,null,58004254,jar,https://data.globe.gov/system/photos/2019/08/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)
176,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,false,null,GLOBE Observer App,null,null,[SEES2019],null,0,identify,NaN,NaN,2019-07-31 14:04:00,0,26.3347,-80.1142,true,null,false,14663,false,null,58004254,"puddle, vehhicle or animal tracks",null,still: lake/pond/swamp,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)
177,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,true,"There are no eggs or larvae, but there are adu...",GLOBE Observer App,null,null,[SEES2019],null,0,identify,NaN,NaN,2019-07-27 18:16:00,0,26.3346,-80.1144,true,null,false,14662,false,null,58004254,discarded: other,null,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)

In [46]:
fl = fl_merged_data.copy()

In [49]:
fl.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 97 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   countryCode_x                                  178 non-null    str
 1   countryName_x                                  178 non-null    str
 2   elevation_x                                    178 non-null    str
 3   landcoversDataSource                           178 non-null    str
 4   landcoversDownwardCaption                      178 non-null    str
 5   landcoversDownwardExtraData                    178 non-null    str
 6   landcoversDownwardPhotoUrl                     178 non-null    str
 7   landcoversDryGround                            178 non-null    str
 8   landcoversEastCaption                          178 non-null    str
 9   landcoversEastClassifications                  178 non-null    str
 10  landcoversEastExtraData                        178 non-null    str
 11  landcoversEastPhotoUrl                         178 non-null    str
 12  landcoversFeature1Caption                      178 non-null    str
 13  landcoversFeature1ExtraData                    178 non-null    str
 14  landcoversFeature1PhotoUrl                     178 non-null    str
 15  landcoversFeature2Caption                      178 non-null    str
 16  landcoversFeature2ExtraData                    178 non-null    str
 17  landcoversFeature2PhotoUrl                     178 non-null    str
 18  landcoversFeature3Caption                      178 non-null    str
 19  landcoversFeature3ExtraData                    178 non-null    str
 20  landcoversFeature3PhotoUrl                     178 non-null    str
 21  landcoversFeature4Caption                      178 non-null    str
 22  landcoversFeature4ExtraData                    178 non-null    str
 23  landcoversFeature4PhotoUrl                     178 non-null    str
 24  landcoversFieldNotes                           178 non-null    str
 25  landcoversGlobeTeams                           174 non-null    str
 26  landcoversLandCoverId                          178 non-null    str
 27  landcoversLeavesOnTrees                        178 non-null    str
 28  landcoversLocationAccuracyM                    178 non-null    str
 29  landcoversLocationMethod                       178 non-null    str
 30  landcoversMeasuredAt                           178 non-null    datetime64[ms]
 31  landcoversMeasurementElevation                 178 non-null    str
 32  landcoversMeasurementLatitude                  178 non-null    str
 33  landcoversMeasurementLongitude                 178 non-null    str
 34  landcoversMucCode                              178 non-null    str
 35  landcoversMucDescription                       178 non-null    str
 36  landcoversMucDetails                           178 non-null    str
 37  landcoversMuddy                                178 non-null    str
 38  landcoversNorthCaption                         178 non-null    str
 39  landcoversNorthClassifications                 178 non-null    str
 40  landcoversNorthExtraData                       178 non-null    str
 41  landcoversNorthPhotoUrl                        178 non-null    str
 42  landcoversRainingSnowing                       178 non-null    str
 43  landcoversSnowIce                              178 non-null    str
 44  landcoversSouthCaption                         178 non-null    str
 45  landcoversSouthClassifications                 178 non-null    str
 46  landcoversSouthExtraData                       178 non-null    str
 47  landcoversSouthPhotoUrl                        178 non-null    str
 48  landcoversStandingWater                        178 non-null    str
 49  landcoversUpwardCaption                        178 non-null    str
 50  landcoversUpwardExtraData                      178 non-null    str
 51  landcoversUpwardPhotoUrl                       178 non-null    str
 52  landcoversUserid                               178 non-null    str
 53  landcoversWestCaption                          178 non-null    str
 54  landcoversWestClassifications                  178 non-null    str
 55  landcoversWestExtraData                        178 non-null    str
 56  landcoversWestPhotoUrl                         178 non-null    str
 57  organizationId_x                               178 non-null    str
 58  organizationName_x                             178 non-null    str
 59  protocol_x                                     178 non-null    str
 60  siteId                                         178 non-null    str
 61  siteName_x                                     178 non-null    str
 62  geometry_x                                     178 non-null    geometry
 63  countryCode_y                                  178 non-null    str
 64  countryName_y                                  178 non-null    str
 65  elevation_y                                    178 non-null    str
 66  mosquitohabitatmapperAbdomenCloseupPhotoUrls   178 non-null    str
 67  mosquitohabitatmapperBreedingGroundEliminated  178 non-null    str
 68  mosquitohabitatmapperComments                  178 non-null    str
 69  mosquitohabitatmapperDataSource                178 non-null    str
 70  mosquitohabitatmapperExtraData                 178 non-null    str
 71  mosquitohabitatmapperGenus                     178 non-null    str
 72  mosquitohabitatmapperGlobeTeams                174 non-null    str
 73  mosquitohabitatmapperLarvaFullBodyPhotoUrls    178 non-null    str
 74  mosquitohabitatmapperLarvaeCount               120 non-null    float64
 75  mosquitohabitatmapperLastIdentifyStage         178 non-null    str
 76  mosquitohabitatmapperLocationAccuracyM         43 non-null     float64
 77  mosquitohabitatmapperLocationMethod            134 non-null    str
 78  mosquitohabitatmapperMeasuredAt                178 non-null    datetime64[ms]
 79  mosquitohabitatmapperMeasurementElevation      178 non-null    int64
 80  mosquitohabitatmapperMeasurementLatitude       178 non-null    float64
 81  mosquitohabitatmapperMeasurementLongitude      178 non-null    float64
 82  mosquitohabitatmapperMosquitoAdults            178 non-null    str
 83  mosquitohabitatmapperMosquitoEggCount          0 non-null      float64
 84  mosquitohabitatmapperMosquitoEggs              178 non-null    str
 85  mosquitohabitatmapperMosquitoHabitatMapperId   178 non-null    str
 86  mosquitohabitatmapperMosquitoPupae             178 non-null    str
 87  mosquitohabitatmapperSpecies                   178 non-null    str
 88  mosquitohabitatmapperUserid                    178 non-null    str
 89  mosquitohabitatmapperWaterSource               178 non-null    str
 90  mosquitohabitatmapperWaterSourcePhotoUrls      178 non-null    str
 91  mosquitohabitatmapperWaterSourceType           178 non-null    str
 92  organizationId_y                               178 non-null    str
 93  organizationName_y                             178 non-null    str
 94  protocol_y                                     178 non-null    str
 95  siteName_y                                     178 non-null    str
 96  geometry_y                                     178 non-null    geometry
dtypes: datetime64[ms](2), float64(5), geometry(2), int64(1), str(87)
memory usage: 135.0 KB

In [51]:
imp_cols = [
    # geometry
    "geometry_y",

    ## season
    "mosquitohabitatmapperMeasuredAt",

    ## mosquito biology
    "mosquitohabitatmapperLarvaeCount",
    "mosquitohabitatmapperMosquitoAdults",
    "mosquitohabitatmapperMosquitoEggs",
    "mosquitohabitatmapperMosquitoPupae",
    "mosquitohabitatmapperSpecies",
    "mosquitohabitatmapperGenus",

    ## water
    "mosquitohabitatmapperWaterSource",
    "mosquitohabitatmapperWaterSourceType",

    "mosquitohabitatmapperBreedingGroundEliminated",

    ## land cover
    "landcoversMucCode",
    "landcoversMucDescription",
    "landcoversStandingWater",
    "landcoversDryGround",
    "landcoversMuddy",
    "landcoversLeavesOnTrees",

    "mosquitohabitatmapperLocationAccuracyM"
]